"""empty message

Revision ID: 02aff39eaca8
Revises: 97d279520f9d
Create Date: 2017-06-15 15:26:26.715083

"""

# revision identifiers, used by Alembic.
revision = '02aff39eaca8'
down_revision = '97d279520f9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('device_ip', sa.String(length=24), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_record', 'device_ip')
    ### end Alembic commands ###
