"""empty message

Revision ID: 08e8f6eaf000
Revises: 709138fb1b75
Create Date: 2017-03-15 09:00:52.510768

"""

# revision identifiers, used by Alembic.
revision = '08e8f6eaf000'
down_revision = '709138fb1b75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syslog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syslog')
    ### end Alembic commands ###
