"""empty message

Revision ID: 0b4af7eb226f
Revises: ea6cedad5ed6
Create Date: 2017-02-07 15:54:00.487437

"""

# revision identifiers, used by Alembic.
revision = '0b4af7eb226f'
down_revision = 'ea6cedad5ed6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_ibfk_2', 'posts', type_='foreignkey')
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('posts_ibfk_1', 'posts', 'alarm_record', ['alarm_id'], ['id'])
    op.create_foreign_key('posts_ibfk_2', 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###
