"""empty message

Revision ID: 0f3966b5cf96
Revises: cfd9b0416222
Create Date: 2017-02-17 12:12:06.806274

"""

# revision identifiers, used by Alembic.
revision = '0f3966b5cf96'
down_revision = 'cfd9b0416222'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_time_range', sa.Column('day_adjust', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_time_range', 'day_adjust')
    ### end Alembic commands ###
