"""empty message

Revision ID: 1ebf861292d0
Revises: 3c5471ec3214
Create Date: 2018-11-26 13:44:43.050516

"""

# revision identifiers, used by Alembic.
revision = '1ebf861292d0'
down_revision = '3c5471ec3214'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t2m_register', sa.Column('dns', sa.String(length=50), nullable=False))
    op.add_column('t2m_register', sa.Column('password', sa.String(length=50), nullable=False))
    op.add_column('t2m_register', sa.Column('timeout', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_t2m_register_dns'), 't2m_register', ['dns'], unique=False)
    op.create_index(op.f('ix_t2m_register_password'), 't2m_register', ['password'], unique=False)
    op.create_index(op.f('ix_t2m_register_timeout'), 't2m_register', ['timeout'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t2m_register_timeout'), table_name='t2m_register')
    op.drop_index(op.f('ix_t2m_register_password'), table_name='t2m_register')
    op.drop_index(op.f('ix_t2m_register_dns'), table_name='t2m_register')
    op.drop_column('t2m_register', 'timeout')
    op.drop_column('t2m_register', 'password')
    op.drop_column('t2m_register', 'dns')
    ### end Alembic commands ###
