"""empty message

Revision ID: 3c5471ec3214
Revises: ef9f4ef1fb4e
Create Date: 2018-11-26 13:34:49.339620

"""

# revision identifiers, used by Alembic.
revision = '3c5471ec3214'
down_revision = 'ef9f4ef1fb4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t2m_register',
    sa.Column('sysid', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=7), nullable=False),
    sa.Column('encryption_method', sa.String(length=30), nullable=False),
    sa.Column('ssurl', sa.String(length=50), nullable=False),
    sa.Column('configurl', sa.String(length=50), nullable=False),
    sa.Column('times', sa.Integer(), nullable=True),
    sa.Column('last_register_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('sysid')
    )
    op.create_index(op.f('ix_t2m_register_configurl'), 't2m_register', ['configurl'], unique=False)
    op.create_index(op.f('ix_t2m_register_encryption_method'), 't2m_register', ['encryption_method'], unique=False)
    op.create_index(op.f('ix_t2m_register_ssurl'), 't2m_register', ['ssurl'], unique=False)
    op.create_index(op.f('ix_t2m_register_username'), 't2m_register', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t2m_register_username'), table_name='t2m_register')
    op.drop_index(op.f('ix_t2m_register_ssurl'), table_name='t2m_register')
    op.drop_index(op.f('ix_t2m_register_encryption_method'), table_name='t2m_register')
    op.drop_index(op.f('ix_t2m_register_configurl'), table_name='t2m_register')
    op.drop_table('t2m_register')
    ### end Alembic commands ###
