"""empty message

Revision ID: 3dde1ce50e35
Revises: badf97c1cc8b
Create Date: 2018-01-15 09:26:51.224655

"""

# revision identifiers, used by Alembic.
revision = '3dde1ce50e35'
down_revision = 'badf97c1cc8b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_list', 'login_name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               nullable=True)
    op.alter_column('device_list', 'login_password',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               nullable=True)
    op.drop_index('ip', table_name='device_list')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ip', 'device_list', ['ip'], unique=True)
    op.alter_column('device_list', 'login_password',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               nullable=False)
    op.alter_column('device_list', 'login_name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               nullable=False)
    ### end Alembic commands ###
