"""empty message

Revision ID: 585f392682ac
Revises: c3020d7d10d4
Create Date: 2017-02-09 09:21:27.425352

"""

# revision identifiers, used by Alembic.
revision = '585f392682ac'
down_revision = 'c3020d7d10d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_configure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=20), nullable=False),
    sa.Column('api_params', sa.String(length=100), nullable=False),
    sa.Column('api_params_value', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_configure')
    ### end Alembic commands ###
