"""empty message

Revision ID: 6c2ad646e8d8
Revises: 02aff39eaca8
Create Date: 2017-06-15 16:05:56.751118

"""

# revision identifiers, used by Alembic.
revision = '6c2ad646e8d8'
down_revision = '02aff39eaca8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_record', 'device_ip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('device_ip', mysql.VARCHAR(length=24), nullable=True))
    ### end Alembic commands ###
