"""empty message

Revision ID: 709138fb1b75
Revises: a41e470fa5ad
Create Date: 2017-03-14 17:47:06.916643

"""

# revision identifiers, used by Alembic.
revision = '709138fb1b75'
down_revision = 'a41e470fa5ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syslog_alarm_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_type', sa.String(length=10), nullable=True),
    sa.Column('alarm_name', sa.String(length=100), nullable=True),
    sa.Column('alarm_level', sa.String(length=10), nullable=True),
    sa.Column('alarm_status', sa.SmallInteger(), nullable=True),
    sa.Column('alarm_keyword', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syslog_alarm_config')
    ### end Alembic commands ###
