"""empty message

Revision ID: 7a93933feaa9
Revises: d972c1bff289
Create Date: 2018-01-07 00:27:44.081911

"""

# revision identifiers, used by Alembic.
revision = '7a93933feaa9'
down_revision = 'd972c1bff289'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcap_order',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=20), nullable=False),
    sa.Column('login_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('question_description', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcap_order_account_id'), 'pcap_order', ['account_id'], unique=False)
    op.create_index(op.f('ix_pcap_order_login_name'), 'pcap_order', ['login_name'], unique=False)
    op.create_index(op.f('ix_pcap_order_username'), 'pcap_order', ['username'], unique=False)
    op.create_table('pcap_result',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('sysid', sa.String(length=100), nullable=True),
    sa.Column('pcap_order_id', sa.String(length=128), nullable=True),
    sa.Column('pcap_filepath', sa.String(length=200), nullable=True),
    sa.Column('r2d2_filepath', sa.String(length=200), nullable=True),
    sa.Column('result_description', sa.String(length=1024), nullable=True),
    sa.Column('speedtest', sa.String(length=50), nullable=True),
    sa.Column('pingtest', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcap_result_pcap_order_id'), 'pcap_result', ['pcap_order_id'], unique=False)
    op.create_index(op.f('ix_pcap_result_sysid'), 'pcap_result', ['sysid'], unique=False)
    op.create_table('pi_register',
    sa.Column('sysid', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('times', sa.Integer(), nullable=True),
    sa.Column('last_register_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('sysid')
    )
    op.create_index(op.f('ix_pi_register_username'), 'pi_register', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pi_register_username'), table_name='pi_register')
    op.drop_table('pi_register')
    op.drop_index(op.f('ix_pcap_result_sysid'), table_name='pcap_result')
    op.drop_index(op.f('ix_pcap_result_pcap_order_id'), table_name='pcap_result')
    op.drop_table('pcap_result')
    op.drop_index(op.f('ix_pcap_order_username'), table_name='pcap_order')
    op.drop_index(op.f('ix_pcap_order_login_name'), table_name='pcap_order')
    op.drop_index(op.f('ix_pcap_order_account_id'), table_name='pcap_order')
    op.drop_table('pcap_order')
    ### end Alembic commands ###
