"""empty message

Revision ID: 97d279520f9d
Revises: 08e8f6eaf000
Create Date: 2017-03-16 16:52:19.593317

"""

# revision identifiers, used by Alembic.
revision = '97d279520f9d'
down_revision = '08e8f6eaf000'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syslog', sa.Column('facility', sa.String(length=20), nullable=True))
    op.add_column('syslog', sa.Column('serverty', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('syslog', 'serverty')
    op.drop_column('syslog', 'facility')
    ### end Alembic commands ###
