"""empty message

Revision ID: badf97c1cc8b
Revises: 7a93933feaa9
Create Date: 2018-01-15 09:24:08.558709

"""

# revision identifiers, used by Alembic.
revision = 'badf97c1cc8b'
down_revision = '7a93933feaa9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snmp_interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('snmp_sysname', sa.String(length=100), nullable=True),
    sa.Column('snmp_if_desc', sa.String(length=50), nullable=True),
    sa.Column('snmp_if_alias', sa.String(length=200), nullable=True),
    sa.Column('snmp_if_physical_status', sa.SmallInteger(), nullable=True),
    sa.Column('snmp_if_protocal_status', sa.SmallInteger(), nullable=True),
    sa.Column('snmp_last_down_time', sa.DateTime(), nullable=True),
    sa.Column('snmp_last_rec_time', sa.DateTime(), nullable=True),
    sa.Column('snmp_last_in_speed', sa.Float(), nullable=True),
    sa.Column('snmp_last_out_speed', sa.Float(), nullable=True),
    sa.Column('data_storage', sa.String(length=100), nullable=True),
    sa.Column('data_path', sa.String(length=100), nullable=True),
    sa.Column('snmp_last_fetch_status', sa.String(length=100), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snmp_interface_device_id'), 'snmp_interface', ['device_id'], unique=False)
    op.create_index(op.f('ix_snmp_interface_snmp_if_desc'), 'snmp_interface', ['snmp_if_desc'], unique=False)
    op.create_table('snmp_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('oid_name', sa.String(length=50), nullable=True),
    sa.Column('oid', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snmp_models_vendor'), 'snmp_models', ['vendor'], unique=False)
    op.add_column('device_list', sa.Column('community', sa.String(length=20), nullable=True))
    op.add_column('device_list', sa.Column('monitor_fail_date', sa.DateTime(), nullable=True))
    op.add_column('device_list', sa.Column('monitor_rec_date', sa.DateTime(), nullable=True))
    op.add_column('device_list', sa.Column('monitor_status', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_device_list_community'), 'device_list', ['community'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_list_community'), table_name='device_list')
    op.drop_column('device_list', 'monitor_status')
    op.drop_column('device_list', 'monitor_rec_date')
    op.drop_column('device_list', 'monitor_fail_date')
    op.drop_column('device_list', 'community')
    op.drop_index(op.f('ix_snmp_models_vendor'), table_name='snmp_models')
    op.drop_table('snmp_models')
    op.drop_index(op.f('ix_snmp_interface_snmp_if_desc'), table_name='snmp_interface')
    op.drop_index(op.f('ix_snmp_interface_device_id'), table_name='snmp_interface')
    op.drop_table('snmp_interface')
    ### end Alembic commands ###
