"""empty message

Revision ID: c3020d7d10d4
Revises: 0b4af7eb226f
Create Date: 2017-02-07 23:43:21.388002

"""

# revision identifiers, used by Alembic.
revision = 'c3020d7d10d4'
down_revision = '0b4af7eb226f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
