"""empty message

Revision ID: cfd9b0416222
Revises: 585f392682ac
Create Date: 2017-02-15 16:19:15.458345

"""

# revision identifiers, used by Alembic.
revision = 'cfd9b0416222'
down_revision = '585f392682ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_time_range', sa.Column('valid_alarm_type', sa.String(20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_time_range', 'valid_alarm_type')
    ### end Alembic commands ###
