"""empty message

Revision ID: d972c1bff289
Revises: 6c2ad646e8d8
Create Date: 2017-07-14 10:04:38.815756

"""

# revision identifiers, used by Alembic.
revision = 'd972c1bff289'
down_revision = '6c2ad646e8d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ont_account_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_id', sa.String(length=256), nullable=False),
    sa.Column('account_info', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ont_account_info')
    ### end Alembic commands ###
