"""empty message

Revision ID: ea6cedad5ed6
Revises: None
Create Date: 2017-02-07 15:10:57.323341

"""

# revision identifiers, used by Alembic.
revision = 'ea6cedad5ed6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=True),
    sa.Column('interface', sa.String(length=10), nullable=True),
    sa.Column('sub_int', sa.String(length=5), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('mac', sa.String(length=30), nullable=True),
    sa.Column('bas_name', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_interface'), 'account', ['interface'], unique=False)
    op.create_index(op.f('ix_account_mac'), 'account', ['mac'], unique=False)
    op.create_index(op.f('ix_account_sub_int'), 'account', ['sub_int'], unique=False)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=False)
    op.create_table('alarm_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=True),
    sa.Column('content_md5', sa.String(length=32), nullable=True),
    sa.Column('alarm_type', sa.SmallInteger(), nullable=True),
    sa.Column('alarm_level', sa.SmallInteger(), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=True),
    sa.Column('lastCallId', sa.String(length=128), nullable=True),
    sa.Column('calledTimes', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('call_group', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_record_call_group'), 'alarm_record', ['call_group'], unique=False)
    op.create_index(op.f('ix_alarm_record_content_md5'), 'alarm_record', ['content_md5'], unique=False)
    op.create_index(op.f('ix_alarm_record_lastCallId'), 'alarm_record', ['lastCallId'], unique=False)
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=30), nullable=False),
    sa.Column('area_desc', sa.String(length=200), nullable=True),
    sa.Column('area_machine_room', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_area_name'), 'area', ['area_name'], unique=False)
    op.create_table('area_machine_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('permit_machine_room', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_machine_room_area_id'), 'area_machine_room', ['area_id'], unique=False)
    op.create_table('call_record_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNum', sa.String(length=20), nullable=True),
    sa.Column('respCode', sa.String(length=10), nullable=True),
    sa.Column('callId', sa.String(length=40), nullable=True),
    sa.Column('createDateInResp', sa.String(length=15), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('call_group', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_record_detail_callId'), 'call_record_detail', ['callId'], unique=False)
    op.create_index(op.f('ix_call_record_detail_call_group'), 'call_record_detail', ['call_group'], unique=False)
    op.create_index(op.f('ix_call_record_detail_createDateInResp'), 'call_record_detail', ['createDateInResp'], unique=False)
    op.create_index(op.f('ix_call_record_detail_phoneNum'), 'call_record_detail', ['phoneNum'], unique=False)
    op.create_index(op.f('ix_call_record_detail_respCode'), 'call_record_detail', ['respCode'], unique=False)
    op.create_table('call_time_range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('range_name', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('stop_time', sa.Time(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_attended_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attended_time_name', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('stop_time', sa.Time(), nullable=False),
    sa.Column('day_adjust', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.Date(), nullable=True),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('attended_time_id', sa.SmallInteger(), nullable=False),
    sa.Column('duty_status', sa.SmallInteger(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_desc',
    sa.Column('job_id', sa.SmallInteger(), nullable=False),
    sa.Column('job_name', sa.String(length=20), nullable=True),
    sa.Column('job_desc', sa.String(length=100), nullable=True),
    sa.Column('alarm_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('machine_room_id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=28), nullable=False),
    sa.Column('customer_number', sa.String(length=64), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_operator'), 'log', ['operator'], unique=False)
    op.create_table('machineroom_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('permit_value', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pon_alarm_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('frame', sa.String(length=2), nullable=True),
    sa.Column('slot', sa.String(length=2), nullable=True),
    sa.Column('port', sa.String(length=3), nullable=True),
    sa.Column('fail_times', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('last_fail_time', sa.DateTime(), nullable=True),
    sa.Column('last_recovery_time', sa.DateTime(), nullable=True),
    sa.Column('alarmed_flag', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('sync_event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('sync_func', sa.String(length=100), nullable=True),
    sa.Column('sync_device', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('stop_time', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_sync_event_sub_id'), 'sync_event', ['sub_id'], unique=False)
    op.create_index(op.f('ix_sync_event_sync_func'), 'sync_event', ['sync_func'], unique=False)
    op.create_table('token_record',
    sa.Column('unique_id', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expire', sa.String(length=10), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('ups_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oid_dict', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('vendeor', sa.String(length=20), nullable=True),
    sa.Column('community', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_notify_callback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNum', sa.String(length=15), nullable=True),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.Column('callId', sa.String(length=40), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_notify_callback_phoneNum'), 'voice_notify_callback', ['phoneNum'], unique=False)
    op.create_table('device_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=30), nullable=False),
    sa.Column('ip', sa.String(length=16), nullable=False),
    sa.Column('login_name', sa.String(length=20), nullable=False),
    sa.Column('login_password', sa.String(length=20), nullable=False),
    sa.Column('machine_room_id', sa.Integer(), nullable=True),
    sa.Column('enable_password', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_room_id'], ['machineroom_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phoneNum', sa.String(length=15), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('duty', sa.Integer(), nullable=True),
    sa.Column('permit_machine_room', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phoneNum')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('alarm_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarm_record.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('device_list')
    op.drop_index(op.f('ix_voice_notify_callback_phoneNum'), table_name='voice_notify_callback')
    op.drop_table('voice_notify_callback')
    op.drop_table('ups_info')
    op.drop_table('token_record')
    op.drop_index(op.f('ix_sync_event_sync_func'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_sub_id'), table_name='sync_event')
    op.drop_table('sync_event')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('pon_alarm_record')
    op.drop_table('machineroom_list')
    op.drop_index(op.f('ix_log_operator'), table_name='log')
    op.drop_table('log')
    op.drop_table('job_desc')
    op.drop_table('duty_schedule')
    op.drop_table('duty_attended_time')
    op.drop_table('call_time_range')
    op.drop_index(op.f('ix_call_record_detail_respCode'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_phoneNum'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_createDateInResp'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_call_group'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_callId'), table_name='call_record_detail')
    op.drop_table('call_record_detail')
    op.drop_index(op.f('ix_area_machine_room_area_id'), table_name='area_machine_room')
    op.drop_table('area_machine_room')
    op.drop_index(op.f('ix_area_area_name'), table_name='area')
    op.drop_table('area')
    op.drop_index(op.f('ix_alarm_record_lastCallId'), table_name='alarm_record')
    op.drop_index(op.f('ix_alarm_record_content_md5'), table_name='alarm_record')
    op.drop_index(op.f('ix_alarm_record_call_group'), table_name='alarm_record')
    op.drop_table('alarm_record')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_sub_int'), table_name='account')
    op.drop_index(op.f('ix_account_mac'), table_name='account')
    op.drop_index(op.f('ix_account_interface'), table_name='account')
    op.drop_table('account')
    ### end Alembic commands ###
