"""empty message

Revision ID: ef9f4ef1fb4e
Revises: ffd248140ac1
Create Date: 2018-04-22 15:37:39.702605

"""

# revision identifiers, used by Alembic.
revision = 'ef9f4ef1fb4e'
down_revision = 'ffd248140ac1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syslog_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=20), nullable=True),
    sa.Column('serverty', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syslog_crit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=20), nullable=True),
    sa.Column('serverty', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syslog_debug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=20), nullable=True),
    sa.Column('serverty', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syslog_emerg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=20), nullable=True),
    sa.Column('serverty', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syslog_err',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=20), nullable=True),
    sa.Column('serverty', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syslog_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=20), nullable=True),
    sa.Column('serverty', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syslog_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=20), nullable=True),
    sa.Column('serverty', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syslog_warn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=20), nullable=True),
    sa.Column('serverty', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=40), nullable=True),
    sa.Column('logmsg', sa.String(length=600), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syslog_warn')
    op.drop_table('syslog_notice')
    op.drop_table('syslog_info')
    op.drop_table('syslog_err')
    op.drop_table('syslog_emerg')
    op.drop_table('syslog_debug')
    op.drop_table('syslog_crit')
    op.drop_table('syslog_alert')
    ### end Alembic commands ###
