"""empty message

Revision ID: ffd248140ac1
Revises: 3dde1ce50e35
Create Date: 2018-01-15 15:24:30.817001

"""

# revision identifiers, used by Alembic.
revision = 'ffd248140ac1'
down_revision = '3dde1ce50e35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_list', sa.Column('mib_model', sa.SmallInteger(), nullable=True))
    op.add_column('device_list', sa.Column('vendor', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_list', 'vendor')
    op.drop_column('device_list', 'mib_model')
    ### end Alembic commands ###
